### ISSUE TITLE
Update Store Component to Have a Buffs Row + Create Manager Component

### ISSUE THREAD

**Issue by leestanley** [acmucsd/cookie-clicker#11]
**Full Store Bar:**
![image](https://user-images.githubusercontent.com/8893880/107900923-3fb90680-6ef7-11eb-91ee-b0b0195991aa.png)

**Manager Component**
![image](https://user-images.githubusercontent.com/8893880/107900947-519aa980-6ef7-11eb-887d-3c558fb9114d.png)

**Comment by Froggerson** [comment]
![image](https://user-images.githubusercontent.com/32044772/111088142-028a6900-84e3-11eb-95d9-45f49f918f3c.png)
it scuffed but thats ok （＾・ω・＾❁）
